
GO

/****** Object:  Table [dbo].[Logradouro]    Script Date: 29/03/2024 17:00:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Logradouro](
	[LogradouroId] [int] IDENTITY(1,1) NOT NULL,
	[LogradouroNome] [varchar](250) NOT NULL,
	[ClienteId] [int] NOT NULL,
 CONSTRAINT [PK_Logradouro] PRIMARY KEY CLUSTERED 
(
	[LogradouroId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

